name: mqtt-broker-snap
base: core24
version: '0.1'
summary: Custom MQTT Broker in Python
description: A minimal MQTT broker written in Python.

grade: stable
confinement: strict  # Usa 'devmode' se vuoi testare senza restrizioni

apps:
  broker:
    command: bin/broker
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  broker:
    plugin: python
    source: src  # Assicurati che 'src/' contenga 'broker.py'
    stage-packages:
      - python3
      - python3-pip
    override-build: |
      set -xe
      chmod +x $SNAPCRAFT_PART_SRC/broker.py
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp $SNAPCRAFT_PART_SRC/broker.py $SNAPCRAFT_PART_INSTALL/bin/broker
